### ISSUE TITLE
Provide type for SkyFileItem errorType

### ISSUE THREAD

**Issue by Blackbaud-IsaacAggrey** [blackbaud/skyux-forms#103]
### Expected behavior

SkyFileItem has an exported type for `errorType` that I can check as a consumer for different types without a 'magic string'.

https://github.com/blackbaud/skyux-forms/blob/master/src/app/public/modules/file-attachment/file-item.ts#L4

### Actual behavior

SKY UX could change the errorType string and my code would break without knowing on an update. It's already effectively exported since I need to check that to distinguish different errors so a type would just help backward compatibility (i.e., as a library, if you export a type you  know you'd more likely break someone if you change it)

**Comment by Blackbaud-SteveBrush** [comment]
Breaking change reason: Even if we list specific `string` that can be used, a consumer's build would fail if they added a string that was not supported.
