### ISSUE TITLE
Skyux component: Attachment file component - url content overflows

### ISSUE THREAD

**Issue by kamalsingh** [blackbaud/skyux-forms#170]
Expected behavior: For large link, partial link should be displayed, follow by "..." 

Actual behavior: Url content overflow

Steps to reproduce: 1. Navigate to file attachment component- https://developer.blackbaud.com/skyux/components/file-attachments/file-attachment
2. Attach a file using link, paste a large link in the "Paste a link to a file" field and click on "Done" button
3. Validate the attachment title

Severity: 3 - Medium

Please check attached file for reference.
![url_Overflow](https://user-images.githubusercontent.com/5894278/90599011-b9568d00-e211-11ea-8a0e-f0b160eb89c6.JPG)

[AB#1556227](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1556227)

**Comment by Blackbaud-AlexKingman** [comment]
This has been fixed in a previous version.
