### ISSUE TITLE
Change default wrapping behavior of checkbox text

### ISSUE THREAD

**Issue by Blackbaud-AdamFunderburk** [blackbaud/skyux-forms#19]
### Expected behavior
Checkbox text should wrap inside their containers, like other form inputs.

### Actual behavior
Checkbox text is set to `nowrap` by default. (Radio buttons are currently set to `white-space: normal`)

### Steps to reproduce
Give a SKY UX 2 checkbox a long text label.

### Impact
Sounds like it is currently affecting Donation Forms.

**Comment by Blackbaud-TrevorBurch** [comment]
In looking into this it appears that both the radio and checkbox are set to `nowrap`. The `normal` on the radio is on the parent element but is `nowrap` when it gets to the label.

**Comment by Blackbaud-TrevorBurch** [comment]
In `skyux-theme` `3.4.1`
