### ISSUE TITLE
Skyux component: Attachment file component - User is not getting error message in case of incorrect file or link

### ISSUE THREAD

**Issue by kamalsingh** [blackbaud/skyux-forms#190]
Expected behavior: User should get the error message

Actual behavior:  User is not getting error message

Steps to reproduce: 1. enter invalid file or link and click on done button, user should get the validation error message
2. Close the error message and try to enter another invalid file or link and click on done button
3. User is not getting validation error message

Severity: 3- Medium

[AB#1573482](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1573482)

**Comment by Blackbaud-DanMiller** [comment]
Hey @kamalsing - how would the component know if the file or link is invalid? Screenshots or screencast of the behavior would be helpful too. Thanks!

**Comment by Blackbaud-SteveBrush** [comment]
A code example would be helpful, too.

**Comment by kamalsingh** [comment]
Hey @Blackbaud-DanMiller, Thanks for response. I am able to see same issue in the given demo code here- https://developer.blackbaud.com/skyux/components/file-attachments/file-attachment.

Below description is only for max file size but this is occurring on all validations-
1. Applied validation for max file size to 4000000
2. If I try to attach a file or a link first time with file size more than mentioned above size then getting max file size error as mentioned in the below attached screenshot.
![maxFileSizeError](https://user-images.githubusercontent.com/5894278/92680450-856e1380-f348-11ea-8233-fc90874968c9.JPG)

3. Now if I don't remove error alert and try to add another file or link then able to see error message successfully.
**4. But If I remove error alert and then try to attach a file or link with file size more than mentioned above size then not getting error on UI.**

**Note:** Sharing my analysis here- 
When we remove error alert then it is not removing that from DOM structure but hiding it from UI. So, when we try to add another file or link with invalid size then it is replacing error message with attached file size error but alert is hidden so we are not able to see it on UI.

**Comment by Blackbaud-TrevorBurch** [comment]
We made an update to our demo to try to help show how alerts should be handled. I verified that we do report rejected files correctly even if there had been a previously rejected file.

NOTE: We changed our demo a while back from an alert to a status indicator based on docs feedback.
