### ISSUE TITLE
Change vertical alignment of checkbox/radio button when text labels wrap.

### ISSUE THREAD

**Issue by Blackbaud-AdamFunderburk** [blackbaud/skyux-forms#20]
### Expected behavior
Our preferred SKY UX design would be for the checkbox/radio glyph to remain aligned to the _first line_ of a wrapped text label.
![image](https://user-images.githubusercontent.com/15896944/52227654-26980c80-287e-11e9-97c1-c7a2647c441c.png)

### Actual behavior
When checkbox or radio button text wraps to additional lines, the glyph is vertically-centered to the height of the text label.

### Steps to reproduce
Give a SKY UX 2 radio button a long text label.

**Comment by Blackbaud-TrevorBurch** [comment]
In `skyux-theme` `3.4.1`
