### ISSUE TITLE
Input box height is 2px larger for input boxes with `input` in Safari

### ISSUE THREAD

**Issue by Blackbaud-PaulCrowder** [blackbaud/skyux-forms#212]
In all browsers but Safari, the height of input boxes that contain an `input type="text"` is 55px. In Safari it is 57px. This is possibly related to how we set the line height on the input element to reduce its height, which doesn't seem to have the desired effect in Safari.

[AB#1592100](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1592100)

**Comment by Blackbaud-AlexKingman** [comment]
@Blackbaud-PaulCrowder Is this still an issue? I'm seeing `input type="text"` are 55px in Safari.

**Comment by Blackbaud-PaulCrowder** [comment]
Perhaps not with the changes @johnhwhite made to line height for input box?

**Comment by johnhwhite** [comment]
> Perhaps not with the changes @johnhwhite made to line height for input box?

#261 switched from a fractional pixel line height to an exact pixel height and that may have addressed this issue in Safari.

**Comment by Blackbaud-AlexKingman** [comment]
Awesome! Its a 2-fer. Closing.
