### ISSUE TITLE
Input box cuts of the bottom of some letters

### ISSUE THREAD

**Issue by Blackbaud-DanGrochmal** [blackbaud/skyux-forms#221]
### Expected behavior

![image](https://user-images.githubusercontent.com/39523611/97475439-a653ed80-1923-11eb-89ee-333f8b821dbe.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/39523611/97475547-c71c4300-1923-11eb-9509-378fa4b386c7.png)

### Steps to reproduce

Enter letters like `y` or `p` into an input box

### Impact

[AB#1615244](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1615244)

**Comment by ThomasOrtiz** [comment]
TNT is also experiencing this with a select dropdown and "g"

![image](https://user-images.githubusercontent.com/10877317/99452336-67490480-28f1-11eb-9b84-6b71620f4dc2.png)
