### ISSUE TITLE
Checkbox first-class support for Angular reactive forms

### ISSUE THREAD

**Issue by Blackbaud-StacyCarlos** [blackbaud/skyux-forms#233]
### Expected behavior
The checkbox component has first-class support for Angular template-driven _or_ reactive forms.

### Actual behavior
Only template-driven forms are supported.

[AB#1690517](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1690517)

**Comment by Blackbaud-AlexKingman** [comment]
Hi @Blackbaud-StacyCarlos, could you show me an example where this isn't working? The checkbox component should work with reactive forms. In the meantime, we're updating the documentation to show some code examples with how to do this.

**Comment by Blackbaud-AlexKingman** [comment]
@Blackbaud-StacyCarlos We've updated the docs to show how to use checkbox with reactive forms. You can view that at the bottom of this page: https://developer.blackbaud.com/skyux-forms/docs/checkbox?docs-active-tab=development

I'm going to close this issue - if you have any questions about the implementation, just let us know! Thanks.
