### ISSUE TITLE
Checkbox - initial state is Dirty if the ngModel value is true

### ISSUE THREAD

**Issue by Blackbaud-JohnHolder** [blackbaud/skyux-forms#36]
### Expected behavior
ngModel should not report as being dirty until it's value is actually changed

### Actual behavior
when the initial value is true, the dirty state will also be true

### Steps to reproduce
```
public checkValue:boolean = true;

<sky-checkbox [(ngModel)]="checkValue" #skycheck="ngModel">
        <sky-checkbox-label>
          sky checkbox {{skycheck.dirty}}{{skycheck.touched}}
        </sky-checkbox-label>
</sky-checkbox>
<input type="checkbox" [(ngModel)]="checkValue" #controlcheck="ngModel" />control checkbox {{controlcheck.dirty}}{{controlcheck.touched}}
```
render the html and notice the reported dirty state of the sky checkbox versus the native checkbox

### Severity
medium

### Impact
causes false positives for validation and submission

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.1.3`
