### ISSUE TITLE
Icon radio button group items should not space between them

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [blackbaud/skyux-forms#43]
<img width="248" alt="Screen Shot 2019-05-23 at 10 41 53 AM" src="https://user-images.githubusercontent.com/4612419/58262027-71636480-7d47-11e9-922f-907b3743d9bd.png">

**Comment by Blackbaud-TrevorBurch** [comment]
Duplicate of https://github.com/blackbaud/skyux-theme/issues/71

I just merged in https://github.com/blackbaud/skyux-forms/pull/42 which will address this.
