### ISSUE TITLE
Component Contribution: Skyux Rich Text Editor

### ISSUE THREAD

**Issue by blackbaud-conorwright** [blackbaud/skyux-forms#71]
**SkyuxRichTextEditorComponent**: https://blackbaud.visualstudio.com/Products/_git/skyux-lib-rich-text-editor
Description: A WYSIWYG form component that allows users to stylize inputted text and outputs an html string to be sanitized and used to later render what they designed.

This is a component that many teams including my own have been needing for a while. We had a meeting with you folks about what was preventing adoption of an external library such as tinymce before and landed on doing internal solutions for now. Over the past few tech-thursdays I decided to work on making a rich text editor just using sky components and base angular. This is the result, it functions pretty well and most of the requirements I got from working with my designer. I also put it into its own library to hopefully make it easier to adopt.

Please have a look and see if it can be used at least as an example. It would be really helpful to have a common editor. And if there's anything else I can do in this library next tech-thursday to improve it and make it a better component candidate, let me know.

Also let me know if there's a better place to put this. I just figured it's a form component so maybe it goes in forms. Though I could also see it getting its own library.

**Comment by Blackbaud-SteveBrush** [comment]
Closing this for now, but @blackbaud-conorwright will be creating an internal-only version of this library to get the ball rolling!

**Comment by blackbaud-conorwright** [comment]
Additional information in the `#1bb-rich-text-editor` channel
