### ISSUE TITLE
Ability to disable the "File Attachment" component

### ISSUE THREAD

**Issue by Blackbaud-KrisMahon** [blackbaud/skyux-forms#8]
### Expected behavior
The "File Attachment" component should support being disabled to allow for more complex and dynamic forms.  All form-level components should support the ability to be disabled and be styled appropriately.

`<sky-file-drop [disabled]="true"></sky-file-drop>`

### Actual behavior
Setting `[disabled]="true"` has no effect - the component is not grayed out and the user can still click/drop to choose a file.

### Severity
Low

### Impact
Low

**Comment by Blackbaud-ToddRoberts** [comment]
Do you have a mockup or other example of where you are disabling a file attach?
