### ISSUE TITLE
Single file attachment > Allow changing the "Choose file" wording

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux-forms#88]

**Comment by blackbaud-johnly** [comment]
The UX guidelines for buttons at https://developer.blackbaud.com/skyux/components/button#ux-guidelines say not to use articles, and this request originated with the desire to add an article to make the button label "Choose a file." I assume we should close this issue unless there is a strong use case for changing the label for other reasons.
